language: node_js
node_js:
- '6'
addons:
  browserstack:
    username: "sebastienvandenb1"
    access_key:
      secure: "iTG5wK7qLB7P4ggpYSdIsyf+aMFkPCqQPdGo6CLvhZ2KL3QQ41SsIEdHGEhlcszsAFWgEEx/5fRurT+2PMWFbub6VkZPhCZ5xI9D0KF4QXRNFGUkmGNrx5qSXHY5yLUCP9BJhxNPHN23ZuFpkMkWW+H46x1oS/Ay42ylzRVOtac="
before_script:
- npm install -g gulp
- cd ./Tools/Gulp
- npm install
script: gulp
notifications:
  slack:
    secure: TBYDAN8Dlkx3dM+Q5ClAZem7agAhQ1oB/fGT665qn7D+j2YfWChvlfXegvXL4LPDmQgbI0UfazcjWId5a0EwmmPkRb+kMJItPiMt5jiIp2WKoZQ+qob6H9tBCRJbbpWM430wiPeKfBfbcZP/XSlpVMWhgU5ogAFDSUKjvHT7IuE=
